@startuml
autonumber "<b>00"
actor User as u 
participant UI as ui
participant Express as e 
participant Node as n 
database DB as db


u -> ui: Trimite datele de autentificare
ui -> e: HTTP /register
group Server
e -> db: Verifica daca utilizatorul exista
db -> e: raspuns
e -> n: Verifica daca datele sunt valida
n -> e: raspuns

e -> db: Salveaza user
end 
e -> ui: Redirectare /login

@enduml
